@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Dec 22 13:28:02 +0700 2022
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim axi_wrapper_tb_behav -key {Behavioral:sim_1:Functional:axi_wrapper_tb} -tclbatch axi_wrapper_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/repo/kuliah/vlsi/imregin_max/matrix_max_tb_behav.wcfg -log simulate.log"
call xsim  axi_wrapper_tb_behav -key {Behavioral:sim_1:Functional:axi_wrapper_tb} -tclbatch axi_wrapper_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/repo/kuliah/vlsi/imregin_max/matrix_max_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
